[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/_internal/*"
  to = "/"
  status = 404
  force = true

# Redirect www to apex domain
[[redirects]]
  from = "https://www.transparent.tools/*"
  to = "https://transparent.tools/:splat"
  status = 301
  force = true
