"""Regression checks for the production tool index and its generated data."""

from __future__ import annotations

import html
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "catalog.json"
INDEX = REPO / "index.html"
METADATA = REPO / "data" / "homepage-tool-meta.json"

BEGIN_MARKER = (
    "<!-- BEGIN static tool links: generated by scripts/inject_seo_meta.py -->"
)
END_MARKER = "<!-- END static tool links -->"


def public_tools() -> list[dict]:
    catalog = json.loads(CATALOG.read_text())
    return [
        entry
        for entry in catalog
        if "templates"
        not in {str(value).strip().lower() for value in entry.get("category", [])}
    ]


def metadata_key(path: str) -> str:
    normalized = re.sub(r"^\./", "/", path)
    return normalized if normalized.endswith("/") else f"{normalized}/"


def test_static_links_match_public_catalog() -> None:
    source = INDEX.read_text()
    block = source.split(BEGIN_MARKER, 1)[1].split(END_MARKER, 1)[0]
    links = [html.unescape(value) for value in re.findall(r'href="([^"]+)"', block)]
    expected = [entry["path"] for entry in public_tools()]
    assert len(links) == len(expected)
    assert sorted(links) == sorted(expected)


def test_homepage_metadata_matches_catalog() -> None:
    tools = public_tools()
    metadata = json.loads(METADATA.read_text())
    assert set(metadata) == {metadata_key(entry["path"]) for entry in tools}
    assert len(metadata) == len(tools)

    versions = {
        metadata_key(entry["path"]): entry.get("version") for entry in tools
    }
    for key, entry in metadata.items():
        assert set(entry) == {"last_updated", "revision_count", "version"}
        assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", entry["last_updated"])
        assert isinstance(entry["revision_count"], int)
        assert entry["revision_count"] > 0
        assert entry["version"] == versions[key]


def test_homepage_has_production_head_and_relative_assets() -> None:
    source = INDEX.read_text()
    lower_source = source.lower()
    assert "noindex" not in lower_source
    assert "homepage prototype" not in lower_source
    assert 'rel="canonical" href="https://transparent.tools/"' in source
    assert 'rel="manifest" href="./manifest.json"' in source
    assert "G-YG3SBRRZFZ" in source
    assert 'src="./shared/homepage-index.js"' in source
    assert 'href="./about.html"' in source
    assert 'href="./legal.html"' in source
    assert 'navigator.serviceWorker.register("./service-worker.js")' in source
    assert "/prototypes/" not in source


def test_service_worker_refreshes_homepage_resources() -> None:
    source = (REPO / "service-worker.js").read_text()
    assert "tt-cache-v2" in source
    assert "key.startsWith('tt-cache-')" in source
    assert "request.mode === 'navigate' || isHomepageData(url)" in source
    assert "./data/homepage-tool-meta.json" in source
    assert "./shared/homepage-index.js" in source


def test_metadata_failure_is_nonfatal() -> None:
    source = (REPO / "shared" / "homepage-index.js").read_text()
    assert "const tools = await loadCatalog(catalogUrl);" in source
    assert "metadata = await loadToolMetadata(metadataUrl);" in source
    assert "loading the catalog without it" in source


def test_catalog_failure_preserves_static_links() -> None:
    source = INDEX.read_text()
    success_block = source.split(".then((catalogTools) => {", 1)[1].split(
        ".catch((error) => {", 1
    )[0]
    assert 'addEventListener("input", renderPage)' in success_block
    assert 'addEventListener("change", renderPage)' in success_block
