
import sys
import os
import math

# Add the project root to sys.path so we can import pycalcs
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from pycalcs import fan_curves

def calculate_ns_si(rpm, flow_m3s, pressure_pa, density=1.204):
    """
    Non-dimensional specific speed (omega * sqrt(Q) / (g * dP / rho)^0.75)
    """
    omega = rpm * 2 * math.pi / 60
    g = 9.80665
    head = pressure_pa / (density * g)
    if head <= 0: return 0
    return (omega * math.sqrt(flow_m3s)) / ((g * head)**0.75)

def calculate_ns_us(rpm, flow_cfm, pressure_in_wg):
    """
    US specific speed (N * sqrt(Q) / dP^0.75)
    N in RPM, Q in CFM, dP in inches w.g.
    """
    if pressure_in_wg <= 0: return 0
    return (rpm * math.sqrt(flow_cfm)) / (pressure_in_wg**0.75)

def analyze_archetypes():
    library = fan_curves.get_fan_library()
    results = []
    
    for arc_id, fan in library.items():
        # Find peak efficiency point
        # If efficiency curve isn't explicit, we use the one generated by the library
        eff_curve = fan.get('efficiency_curve', [])
        if not eff_curve:
            continue
            
        peak_idx = 0
        max_eff = -1
        for i, pt in enumerate(eff_curve):
            if pt[1] > max_eff:
                max_eff = pt[1]
                peak_idx = i
        
        q_opt = fan['pressure_curve'][peak_idx][0] # m3/s
        p_opt = fan['pressure_curve'][peak_idx][1] # Pa
        rpm = fan['reference_speed_rpm']
        
        # Convert to US units for comparison
        q_opt_cfm = fan_curves.convert_flow(q_opt, 'm3/s', 'CFM')
        p_opt_in_wg = fan_curves.convert_pressure(p_opt, 'Pa', 'in_wg')
        
        ns_si = calculate_ns_si(rpm, q_opt, p_opt)
        ns_us = calculate_ns_us(rpm, q_opt_cfm, p_opt_in_wg)
        
        results.append({
            'id': arc_id,
            'name': fan['title'],
            'q_opt_m3s': q_opt,
            'p_opt_pa': p_opt,
            'q_opt_cfm': q_opt_cfm,
            'p_opt_in_wg': p_opt_in_wg,
            'rpm': rpm,
            'max_eff': max_eff,
            'ns_si': ns_si,
            'ns_us': ns_us
        })
    
    # Sort by specific speed (high to low, i.e., axial to centrifugal)
    results.sort(key=lambda x: x['ns_si'], reverse=True)
    
    print(f"{'Fan Type':<40} | {'Ns (SI)':<10} | {'Ns (US)':<10} | {'Peak Eff':<10}")
    print("-" * 80)
    for r in results:
        print(f"{r['name']:<40} | {r['ns_si']:<10.3f} | {r['ns_us']:<10.0f} | {r['max_eff']:<10.2%}")
        
    print("\nObservation:")
    print("- High Specific Speed (Ns > 2.0 SI / 40,000 US): Axial fans")
    print("- Medium Specific Speed (Ns 0.5-2.0 SI / 10,000-40,000 US): Mixed-flow fans")
    print("- Low Specific Speed (Ns < 0.5 SI / 10,000 US): Centrifugal fans")

def recommend_fan_type(q_m3s, p_pa, rpm, density=1.204):
    """
    Recommend a fan type based on required duty point and speed.
    """
    ns = calculate_ns_si(rpm, q_m3s, p_pa, density)
    
    recommendation = ""
    if ns > 2.0:
        recommendation = "Axial Fan (Propeller or Tube-axial)"
    elif ns > 1.2:
        recommendation = "High-speed Axial or Mixed-flow Fan"
    elif ns > 0.6:
        recommendation = "Mixed-flow or Backward-Curved Centrifugal Fan"
    elif ns > 0.2:
        recommendation = "Centrifugal Fan (Backward-Curved or Airfoil)"
    else:
        recommendation = "Centrifugal Fan (Forward-Curved or Radial-Tip)"
    
    # Calculate optimal diameter using Cordier correlation (rough)
    # Ds = 1.93 / Ns^0.6
    # D = Ds * sqrt(Q) / (dP/rho)^0.25
    g = 9.80665
    head_rise = p_pa / density
    if ns > 0:
        ds_opt = 2.0 / (ns**0.6) # Simplified Cordier
        d_opt = ds_opt * math.sqrt(q_m3s) / (head_rise**0.25)
    else:
        d_opt = 0
        
    return {
        'ns': ns,
        'recommendation': recommendation,
        'optimal_diameter_m': d_opt
    }

def run_interactive_demo():
    print("\n--- Fan Selection Recommender Prototype ---")
    try:
        # Example duty point: 1.0 m3/s @ 500 Pa, 1800 RPM
        q = 1.0
        p = 500.0
        rpm = 1800.0
        
        rec = recommend_fan_type(q, p, rpm)
        
        print(f"Duty Point: {q} m3/s @ {p} Pa, {rpm} RPM")
        print(f"Calculated Specific Speed (Ns SI): {rec['ns']:.3f}")
        print(f"Recommended Type: {rec['recommendation']}")
        print(f"Estimated Optimal Diameter: {rec['optimal_diameter_m']:.3f} m ({rec['optimal_diameter_m']*1000:.1f} mm)")
        
        # Another example: High pressure, low flow
        q2 = 0.1
        p2 = 1500.0
        rpm2 = 3000.0
        rec2 = recommend_fan_type(q2, p2, rpm2)
        print(f"\nDuty Point: {q2} m3/s @ {p2} Pa, {rpm2} RPM")
        print(f"Calculated Specific Speed (Ns SI): {rec2['ns']:.3f}")
        print(f"Recommended Type: {rec2['recommendation']}")
        print(f"Estimated Optimal Diameter: {rec2['optimal_diameter_m']:.3f} m ({rec2['optimal_diameter_m']*1000:.1f} mm)")

    except Exception as e:
        print(f"Error in demo: {e}")

if __name__ == "__main__":
    analyze_archetypes()
    run_interactive_demo()
