#!/usr/bin/env python3
"""Generate sitemap.xml from catalog.json — single source of truth.

Run from repo root (or anywhere; paths are resolved relative to this file):

    python3 scripts/generate_sitemap.py

Wired into the Netlify build command so the sitemap never drifts from the
catalog again. Excludes example/prototype tools. Verified tools sort first and
get a higher priority.
"""
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "catalog.json"
SITEMAP = REPO / "sitemap.xml"
BASE = "https://transparent.tools"

# Tools we never want indexed (demos / scratch prototypes).
EXCLUDE_PREFIXES = ("example_tool", "unit_conversion_prototyping")

STATIC_PAGES = [
    ("/", "weekly", "1.0"),
    ("/about.html", "monthly", "0.5"),
    ("/legal.html", "yearly", "0.3"),
]


def tool_slug(path: str) -> str | None:
    m = re.search(r"tools/([^/]+)/", path)
    return m.group(1) if m else None


def build_entries() -> list[tuple[str, str, str]]:
    catalog = json.loads(CATALOG.read_text())
    tools = []
    for entry in catalog:
        slug = tool_slug(entry.get("path", ""))
        if not slug or slug.startswith(EXCLUDE_PREFIXES):
            continue
        verified = "human-verified" in entry.get("tags", [])
        priority = "0.8" if verified else "0.6"
        # sort key: verified first, then alphabetical
        tools.append((0 if verified else 1, slug, priority))
    tools.sort(key=lambda t: (t[0], t[1]))
    return [(f"/tools/{slug}/", "monthly", priority) for _, slug, priority in tools]


def render(entries: list[tuple[str, str, str]]) -> str:
    lastmod = date.today().isoformat()
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        "  <!-- Generated by scripts/generate_sitemap.py — do not edit by hand -->",
    ]

    def block(loc: str, changefreq: str, priority: str) -> None:
        lines.extend(
            [
                "  <url>",
                f"    <loc>{BASE}{loc}</loc>",
                f"    <lastmod>{lastmod}</lastmod>",
                f"    <changefreq>{changefreq}</changefreq>",
                f"    <priority>{priority}</priority>",
                "  </url>",
            ]
        )

    lines.append("  <!-- Main pages -->")
    for loc, cf, pr in STATIC_PAGES:
        block(loc, cf, pr)
    lines.append("  <!-- Tools (from catalog.json) -->")
    for loc, cf, pr in entries:
        block(loc, cf, pr)
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def main() -> None:
    entries = build_entries()
    SITEMAP.write_text(render(entries))
    print(f"Wrote {SITEMAP.relative_to(REPO)} with {len(entries)} tools "
          f"+ {len(STATIC_PAGES)} static pages.")


if __name__ == "__main__":
    main()
